name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository...
        uses: actions/checkout@v2
      - name: Run tests...
        uses: ./.github/action-test
      - name: Deploy documentation...
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'fcpp-doc.surge.sh'
          project: './src/doc/html'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
